namespace NDepend.Mcp.Tools.CodeQuery;

internal partial class CodeQueryFeature {
    internal const string LINE_OF_CODE_PROMPT =
          """
          # LINE OF CODE (LOC) METRICS
          
          The property NbLinesOfCode (uint?) is defined on ICodeContainer elements.
          The ICodeContainer interface is implemented by ICodeBase, IAssembly, INamespace, IType, and IMethod.
          
          This property returns null in the following cases:
          
          - The code element is abstract (interface, abstract method).
          - The code element is defined in a referenced or third-party assembly.
          - No PDB file was resolved at analysis time for the parent assembly.
          
          When NbLinesOfCode is null due to missing PDB information, you can use the NbILInstructions (uint?) property instead.
                  
          ## DEFINITION:
          
          The LOC of a method represents the number of executable statements in the source code.
          It is computed from the number of sequence points associated with the method in the PDB file.
          A sequence point identifies a location in the IL code that maps to a specific position in the original source code.
          
          As a result, the LOC metric measures the number of **logical lines of code**, not physical lines.
          
          For type, namespace and assembly elements, the LOC is the sum of the LOC of all contained methods.
          
          ## REMARKS:
          
          - Interfaces, abstract methods and enumerations have a NbLinesOfCode value equals to null.
            Only concrete code that is effectively executed is considered when computing LoC.
          - Namespaces, types, fields and methods declarations are not considered as line of code because they don’t have corresponding sequence points.
          - Blank lines, Comment-only lines, Opening/closing braces on their own lines, Namespace/using declarations are not considered as line of code.
          - When the C# or VB.NET compiler faces an inline instance fields initialization, it generates a sequence point for each of the instance constructor (the same remark applies for inline static fields initialization and static constructor).
          - LoC computed from an anonymous method doesn’t interfere with the LoC of its outer declaring methods.
          - The overall ratio between NbILInstructions and LOC (in C# and VB.NET) is usually around 7.
          
          ## RECOMMENDATIONS:
          
          - Methods where NbLinesOfCode is higher than 20 are hard to understand and maintain.
          - Methods where NbLinesOfCode is higher than 40 are extremely complex and should be split in smaller methods (except if they are automatically generated by a tool).
          
          ## USAGE PATTERNS:
          
          ```csharp
          //<Name>Large methods with declining maintainability</Name>
          from m in JustMyCode.Methods
          where (m.NbLinesOfCode ?? 0) > 30
          where (m.MaintainabilityIndex ?? 100) < 65
          select new {
              m,
              LOC = m.NbLinesOfCode,
              MI = m.MaintainabilityIndex
          }
          ```
          
          ## BEST PRACTICES:
          
          1. Always handle null coverage values using:
             - Null checks: where m.NbLinesOfCode != null
             - Null coalescing: m.NbLinesOfCode ?? 0
          
          2. Exclude generated code from coverage analysis:
             - where !m.IsGeneratedByCompiler (skip generated code)
             - use code base view JustMyCode
          
          3. Combine with other metrics:
             - MaintainabilityIndex (overall maintainability)
             - HalsteadVolume (information density)
             - CyclomaticComplexity (control flow)
             - PercentageCoverage (testing)
          """;
}
